# Generated by Django 4.2.4 on 2023-08-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
